version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu/promo_scraper
permissions:
  - object: /home/ubuntu/promo_scraper
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
      - location: scripts/clean_instance.sh
        timeout: 300
        runas: ubuntu
        onsuccess:
          - echo "BeforeInstall hook succeeded!"
        onerror:
          - echo "BeforeInstall hook failed!"
  AfterInstall:
      - location: scripts/instance_os_dependencies.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/python_dependencies.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/gunicorn.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/nginx.sh
        timeout: 300
        runas: ubuntu
        onsuccess:
          - echo "AfterInstall hook succeeded!"
        onerror:
          - echo "AfterInstall hook failed!"
  ApplicationStop:
      - location: scripts/stop_app.sh
        timeout: 300
        runas: ubuntu
  ApplicationStart:
      - location: scripts/start_app.sh
        timeout: 300
        runas: ubuntu
        onsuccess:
          - echo "ApplicationStart hook succeeded!"
        onerror:
          - echo "ApplicationStart hook failed!"