# Generated by Django 3.1 on 2023-05-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='link',
            field=models.URLField(max_length=350),
        ),
    ]
